### ISSUE TITLE
Tycho `tycho-surefire-plugin:3.0.0-SNAPSHOT:test` is unable to resolve dependencies from the same reactor

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse/tycho#1129]
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-206/2/console stated failing today with 

```
 [ERROR]   Software being installed: org.eclipse.jdt.core.tests.compiler 3.12.1950.qualifier
 [ERROR]   Missing requirement: org.eclipse.jdt.core.tests.compiler 3.12.1950.qualifier requires 'osgi.bundle; org.eclipse.jdt.annotation [2.0.0,3.0.0)' but it could not be found
```

When we used tycho version 2.7.3 the build passed the failure point https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-206/5/console

I think recent changes to tycho might be causing this problem

Notifications: @jarthana

**Comment by laeubi** [comment]
@sravanlakkimsetti thanks for your report, can you tell if `org.eclipse.jdt.core.tests.compiler` is doing something "special", e.g does it depend on additional requirements in the pom, build properties or something else not expressed in the manifest? Is there anything special with `org.eclipse.jdt.annotation` or is it a regular bundle build by Tycho in the same reactor?

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti thanks for your report, can you tell if `org.eclipse.jdt.core.tests.compiler` is doing something "special", e.g does it depend on additional requirements in the pom, build properties or something else not expressed in the manifest? Is there anything special with `org.eclipse.jdt.annotation` or is it a regular bundle build by Tycho in the same reactor?

There are 2 `org.eclipse.jdt.annotation` bundles one with 1.x version and another with 2.x version. Both gets built in the same reactor. 1.x is used only for java 7 and below, so resolving with 2.x is good enough here.

`org.eclipse.jdt.core.tests.compiler` does not have any additional requirements. But `org.eclipse.jdt.annotation` is somewhat special with two bundles with different versions getting built in the same reactor. Need to resolve with 2.x (latest version)

**Comment by laeubi** [comment]
@sravanlakkimsetti do you think you can derive an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test)/example project to demonstrate the issue? With current tycho3.x you need to pass `-Dtycho.resolver.classic=false` to enable the new resolver that has shown this initially in jdt.

**Comment by laeubi** [comment]
Could it be a problem with PR/Baseline replace? We also see this problem without the new resolver...

**Comment by iloveeclipse** [comment]
Could we please have a hot fix or revert to original Tycho state? JDT PR's can't be confirmed anymore.
Ir to which Tycho version one could refer in JDT to get builds running again?

**Comment by laeubi** [comment]
2.7.3 should work according to @sravanlakkimsetti it would be good to know if 2.74 also works. Beside this, there seems no such integration test for tycho currently, so if one could derive a smaller example we can use as a reproducer it would help to fix and prevent such breakage in the future.

**Comment by sravanlakkimsetti** [comment]
I tested with 2.7.3 and it works. I added `-Dtycho.version=2.7.3` to the maven command in jenkinsfile. That worked for me.

**Comment by iloveeclipse** [comment]
@sravanlakkimsetti : would you push that to jdt please?

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti : would you push that to jdt please?

https://github.com/eclipse-jdt/eclipse.jdt.core/pull/219

**Comment by sravanlakkimsetti** [comment]
@laeubi I could not extract a test case for this one but based on testing here are my observations:

org.eclipse.jdt.core.tests.compiler has both versions of jdt.annotation in the Require-bundle as optional bundles. See https://github.com/eclipse-jdt/eclipse.jdt.core/blob/a9cbab31b93daf02def76b4ea63922df61820b74/org.eclipse.jdt.core.tests.compiler/META-INF/MANIFEST.MF#L24 
To succeed I have to remove `org.eclipse.jdt.annotation;bundle-version="[1.1.0,2.0.0)";resolution:=optional,` only then the build proceeds.

Here are the steps to reproduce
1. Clone https://github.com/eclipse-jdt/eclipse.jdt.core
2. update https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/pom.xml to have only 3 modules  <module>org.eclipse.jdt.annotation</module>
    <module>org.eclipse.jdt.annotation_v1</module>
    <module>org.eclipse.jdt.core.tests.compiler</module>

**Comment by stephan-herrmann** [comment]
> > 1. If it works without, why one would require both here?
> > 2. Why `resolution:=optional` if one wants to have them included?
> 
> @jarthana, @stephan-herrmann can you help us here?

If you look at the history of that MANIFEST.MF, you'll see that over the years JDT has tried just about every possibly permutation of wide range vs. specific versions, optional vs. non-optional. Apparently, there is no canonical way how tycho can be convinced to resolve both versions, as each variant seems to have caused failure with one specific version of tycho.

Why we need both? Because the annotations in those versions cause the compiler to apply different semantics during static analysis. Obviously, both need to be tested.

There have been thoughts to discontinue building the v1 variant, but then the build would need a stable address where it can be resolved from. I guess we didn't want to add a previous version of Eclipse to the target platform, but short of that, no location provides a "frozen" version 1.x of o.e.j.annotation.

Also note, that optional dependencies are a typical idiom to simulate a build-time-only dependency (for lack of an option to say so explicitly).

**Comment by laeubi** [comment]
> Also note, that optional dependencies are a typical idiom to simulate a build-time-only dependency (for lack of an option to say so explicitly).

So actually you don't want that at the test, but on the build path? Because including both (from OSGi perspective) do not make much sense here and I just don't understand yet how JDT actually access those in the tests? Are they loaded by the jar? Reflection? Classes parsed directly?

> but then the build would need a stable address where it can be resolved from.

Is it deployed to maven? Then you can consume it from there ...

**Comment by laeubi** [comment]
By the way, maybe extra-requirements are more what you are looking for?

https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#dependency-resolution

**Comment by stephan-herrmann** [comment]
> So actually you don't want that at the test, but on the build path?

No, that's not what I meant. I just wanted to say that optional dependency to this bundle is a common pattern.

> Because including both (from OSGi perspective) do not make much sense here 

Why not? OSGi has no problems with different versions of the same thing.

> and I just don't understand yet how JDT actually access those in the tests? Are they loaded by the jar? Reflection? Classes parsed directly?

```
			String version = this.complianceLevel >= ClassFileConstants.JDK1_8 ? "[2.0.0,3.0.0)" : "[1.1.0,2.0.0)";
			Bundle[] bundles = org.eclipse.jdt.core.tests.compiler.Activator.getPackageAdmin().getBundles("org.eclipse.jdt.annotation", version);
			File bundleFile = FileLocator.getBundleFileLocation(bundles[0]).get();
```

i.e., we get the resolved bundle right from OSGi/equinox. From there it's file access as we put the bundle on the classpath of a test project.

**Comment by stephan-herrmann** [comment]
> By the way, maybe extra-requirements are more what you are looking for?
> 
> https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#dependency-resolution

If you ask me, tycho should be happy that our tests challenge this legal situation. As long as OSGi can handle the thing (as proven by successful test executions in the IDE), I don't see reasons to try the umptieth variant of expressing these dependencies just to please tycho.

**Comment by laeubi** [comment]
From the Tycho side, I think this is caused because Tycho now refuses to add the same dependency in different version, I'll prepare a patch. Beside this, I think this would also be possible to solve by adding an explicit maven dependency to the both other projects in different versions, but this construct remains fragile:

1. On the maven side, one dependency will shade the other and its is a matter of build-path order if you get one or the other and tycho do not maintain any order here so it might be random.
2. On OSGi side, you will merge both classpathes and shading one over the other and thus effectively will have only the first or the second (not sure if order of required bundles matter)

> Why not? OSGi has no problems with different versions of the same thing.

As explained lately, that is not completely true, as long as you have different bundles, if the **same** bundle requires different versions this is not allowed. This only "works" as require-bundle is special in the sense that it just merges your class-space but you are shading one of the other and thus it might not work as expected.

> If you ask me, tycho should be happy that our tests challenge this legal situation.

Not everything that is legal is desired, and not everything that is legal should be recommended...

And actually if @sravanlakkimsetti is correct that the build/test runs without the both optional requires then it seems your test-suite even can't cover what you expect here...

> we get the resolved bundle right from OSGi/equinox.

Yes, but then the require-bundle here is not in charge, you are not using the OSGi classloader here, and your test should better install this as separate bundles.

> Also note, that optional dependencies are a typical idiom to simulate a build-time-only dependency (for lack of an option to say so explicitly).

I cannot recommend this, this is not "typical" because either its optional (that mean your code need to work without it!) or not, but can't be both, I even would suspect that OSGi at runtime only chooses one of both and otherwhise it won't resolve at all.

If you really want to include additional stuff in the test **runtime** then https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#dependency-resolution is the way to go for the P2 part and https://www.eclipse.org/tycho/sitedocs/tycho-surefire-plugin/test-mojo.html#dependencies for the test-part.

**Comment by stephan-herrmann** [comment]
> And actually if @sravanlakkimsetti is correct that the build/test runs without the both optional requires then it seems your test-suite even can't cover what you expect here...

I'm not sure he meant that tests succeed, or whether just launching the tests worked.

Years of successfully running these tests are not a hint that something must have been working, prior to recent changes in tycho?

**Comment by laeubi** [comment]
Beside that, if that behavior is important to you (or JDT) the best thing is to provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the use-case, anything not covered by an integration test is just best effort given the current tycho-dev team size.

**Comment by laeubi** [comment]
Just some notes about the code:

```
String version = this.complianceLevel >= ClassFileConstants.JDK1_8 ? "[2.0.0,3.0.0)" : "[1.1.0,2.0.0)";
			Bundle[] bundles = org.eclipse.jdt.core.tests.compiler.Activator.getPackageAdmin().getBundles("org.eclipse.jdt.annotation", version);
			File bundleFile = FileLocator.getBundleFileLocation(bundles[0]).get();
```

1. PackageAdmin is **deprecated** you should simply iterate the Bundles via the `BundleContext.getBundles()` and select those matching the (OSGi)Version range you desire.
2. `File bundleFile = FileLocator.getBundleFileLocation(bundles[0]).get();` requires a file-system and is Eclipse/Equinox specific, you can use `org.osgi.framework.Bundle.getEntry(String)` / `org.osgi.framework.Bundle.findEntries(String, String, boolean)` to fetch content from a Bundle in a framework independent way.

**Comment by laeubi** [comment]
> One more thought:

Just one more hint to not raise false expectations:
The limitations of PDE are not the limitations of Tycho ... requiring a bundle optionally to let it included in the test-runtime is a workaround for such limitations and are better addressed at PDE directly.

**Comment by stephan-herrmann** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> 
>     1. PackageAdmin is **deprecated** you should simply iterate the Bundles via the `BundleContext.getBundles()` and select those matching the (OSGi)Version range you desire.

I know. Back then I asked the expert, Tom Watson, about alternatives to PackageAdmin, who replied that not all of its functionality is available by other means, but I shouldn't worry, as PackageAdmin is destined to stay, despite the deprecation.

It doesn't affect the current problem, though, does it?

**Comment by stephan-herrmann** [comment]
> 2\. ... requires a file-system and is Eclipse/Equinox specific

Thanks, for productive code this might be useful, but for tests that are not intended for any other context than Eclipse, being Eclipse specific doesn't look like a problem :)

**Comment by stephan-herrmann** [comment]
> Just one more hint to not raise false expectations:
> The limitations of PDE are not the limitations of Tycho ... requiring a bundle optionally to let it included in the test-runtime is a workaround for such limitations and are better addressed at PDE directly.

What limitations of PDE are you referring to? In the IDE I don't see any tooling specific problem.

Or are you saying PDE shouldn't *allow* the current setup in the first place?

And/or is it Equinox that admits things it shouldn't?

We need a solution that all three, PDE, Equinox and tycho understand. Until recently we had such solution, that's why fingers are pointing to the component that changed. If that solution is "wrong" by any definition, then please let me know, which rule is violated, so we can follow-up in other components.

**Comment by mickaelistria** [comment]
> From the Tycho side, I think this is caused because Tycho now refuses to add the same dependency in different version, I'll prepare a patch

I think this can be interpreted as a severe regression. Too bad this wasn't covered by a test to detect it earlier. Are you planning to add one together with your patch? If not, I may be able to spend some time on it tonight or tomorrow.

**Comment by laeubi** [comment]
> I think this can be interpreted as a severe regression.

Sorry this "use-case" is completely alien, I have never seen, nor require this and the result is complete wrecked.

> Are you planning to add one together with your patch?

No this is not anything that ever should be used and is a complete misuses of require bundle to tell PDE it should include something that is completely unrelated to the bundle under test.

> What limitations of PDE are you referring to? In the IDE I don't see any tooling specific problem.

What you actually want is telling PDE that it should include additional stuff in the executed test-runtime, that is something one actually would adjust the run configuration in the IDE and using additional requirements in Tycho. PDE just misses a way to declare so in a way you can share, I already have suggested such things to PDE but it has not got much attention.

> And/or is it Equinox that admits things it shouldn't?

Equinox is not to blame here, because technically that is possible, it just has not the desired effect that you maybe assume here, your 2.0 version simply completely hides what 1.0 provides, and as both are optional OSGi can even ignore one or even both if it decides to be required.

What you actually wan't is to include other bundles together with your bundle, the P2 way would be a p2.inf with additional IU requirements (similar as SWT does to require its fragments from the host), this should then work in P2, in Tycho in PDE and implicitly in OSGi as well.

**Comment by mickaelistria** [comment]
> Sorry this "use-case" is completely alien, I have never seen, nor require this and the result is complete wrecked.

Well maybe it is, but it's still an important story that needs to be supported. But if https://github.com/eclipse/tycho/pull/1142 fixes it, then it's all good.

> No this is not anything that ever should be used and is a complete misuses of require bundle to tell PDE it should include something that is completely unrelated to the bundle under test.

Could you contribute to JDT a better solution? If not, as it's indeed a tricky case that we don't want to break without better solution, I'll add an integration test to avoid breaking JDT again in the future.

**Comment by laeubi** [comment]
> Well maybe it is, but it's still an important story that needs to be supported.

You maybe over estimate the importance, this is nothing Tycho should really support, as it is completely wrecked. I even wonder that Maven do not complains about this case (maybe because we inject the dependencies after the model validation).

> Could you contribute to JDT a better solution? If not, as it's indeed a tricky case that we don't want to break without better solution,

I'm a bit to busy at the moment with some real problems (e.g. ECJ compiler concurrency issue) so don't expect much here, basically https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/META-INF/p2.inf shows how to require additional bundles/fragments, still I think PDE should better support the user, but maybe PDE would argue that this can be archived by editing the runconfig ....

**Comment by stephan-herrmann** [comment]
> @[laeubi](https://github.com/laeubi) closed this as [completed](https://github.com/eclipse/tycho/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/eclipse/tycho/pull/1142 [21 minutes ago](https://github.com/eclipse/tycho/issues/1129#event-6996019369)

thanks

**Comment by sravanlakkimsetti** [comment]
Thanks @mickaelistria for the testcase
