### ISSUE TITLE
assemble-maven-repository should respect the skip=true of maven-deployer-plugin

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#201]
See https://github.com/eclipse/jetty.project/pull/6404#pullrequestreview-716520468

**Comment by olamy** [comment]
@laeubi https://github.com/eclipse/tycho/pull/204

**Comment by mickaelistria** [comment]
I'm not sure Tycho is the best place where to fix that; it looks like this is a Jetty specific workaround pushed into Tycho. If so,we should avoid that and leave problems where they are instead of adding responsibility elsewhere.
Why are some test artifacts considered as dependencies in 1st place?

**Comment by laeubi** [comment]
> it looks like this is a Jetty specific workaround

Nope, this is an enhancement to the reactor projects assembly that needs to ignore projects that are not deployed later on. Otherwise artifacts can be part of the update-site that are never deployed to the maven-repository.

**Comment by mickaelistria** [comment]
We cannot.know.during 1 execution of the reactor whether the.artifacts were or will be.deployed in other reactor executiona. So we shouldn't try to infer too much from the current reactor, that would lead to incorrect results in some cases.
What's the root cause? Why are test deps included.in the case of Jetty p2 repo?

**Comment by cdietrich** [comment]
afaik we have at mwe one reactor where we assemble a repository, but dont publish the repository to maven central. 
https://github.com/eclipse/mwe/blob/1b9beeb59f5df348c3a8d32e0701281fba69570d/maven/org.eclipse.emf.mwe2.repository/pom.xml#L15
https://github.com/eclipse/mwe/blob/1b9beeb59f5df348c3a8d32e0701281fba69570d/maven/org.eclipse.emf.mwe2.parent/pom.xml#L176

so i assume in this would no longer work as the repo will  no longer be assembled.
so maybe we at least need an opt out.

**Comment by laeubi** [comment]
@mickaelistria sorry but I don't understand... For sure it is *possible* to deploy any artifact at any time and delete it even probably but that's a bit strange to assume such things as the default. If ever there is a demand we can still add a flag to include even non deployed artifacts.

@cdietrich this has nothing to do with any pre-2.4.x functionality you might be using and don't affect anything related to deploying a repository itself. So I don't think your case is affected here.

**Comment by olamy** [comment]
Jetty project contains some artifacts/modules which are only used for testing (war or jars) by other modules or even some modules which contains only integration tests.
Those modules simply don't need to be distributed because it makes no sense to be available for consuming by other projects. That's why Jetty project skip deployment of those modules to Maven central.
Jetty project can remove or totally change those modules between versions depending on the tests need.
This is a very common use case in various Maven projects. 
As Jetty do not deploy those modules as part of our release we just want to be able to skip them as well not being part of published p2 site.
I hope this makes sense.
