### ISSUE TITLE
Runtime dependencies not resolved from target file

### ISSUE THREAD

**Issue by akurtakov** [eclipse/tycho#447]
Using https://git.eclipse.org/c/platform/eclipse.platform.releng.aggregator.git/tree/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target - objenesis is removed and and includeDependencyScope="runtime" fails resolution with:
Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.ui.tests 3.15.500.qualifier
[ERROR]   Missing requirement: org.mockito.mockito-core 4.1.0 requires 'java.package; org.objenesis [3.1.0,4.0.0)' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.ui.tests 3.15.500.qualifier depends on: osgi.bundle; org.mockito.mockito-core 2.13.0

@laeubi objenesis is supposed to be resolved as it's transitive runtime dependency of mockito as per https://repo1.maven.org/maven2/org/mockito/mockito-core/4.1.0/mockito-core-4.1.0.pom, right?

**Comment by akurtakov** [comment]
For the record same failures with includeDependencyScope="compile" if objenesis is not explicitly added.

**Comment by laeubi** [comment]
> objenesis is supposed to be resolved as it's transitive runtime dependency of mockito

At least that's what I would expect as per the dependency tree:

![grafik](https://user-images.githubusercontent.com/1331477/146635751-e98d353e-3be0-4b4d-a832-fef0028fce85.png)

Also the m2e target list it even though I noticed that currently we only have compile+test in the UI and thus it should not be shown wen selecting "compile" (as indicated by the grey text from the dependency tree).
![grafik](https://user-images.githubusercontent.com/1331477/146635856-0042b396-379b-4e2c-a2f3-087634d5bab4.png)

According to https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

### provided
This is much like `compile`, but indicates you expect the JDK or a container to provide the dependency at runtime. For example, when building a web application for the Java Enterprise Edition, you would set the dependency on the Servlet API and related Java EE APIs to scope provided because the web container provides those classes**. A dependency with this scope is added to the classpath used for compilation and test, but not the runtime classpath. It is not transitive.**

So I think we have two options here:

1. `compile` scope should include `runtime` scope
2. we explicitly allow to select  `runtime` scope

**Comment by laeubi** [comment]
Sorry for confusion, m2e-pde with current snapshot version also filter this out:

![grafik](https://user-images.githubusercontent.com/1331477/146635981-15b9a429-b7b3-47ac-ac65-a584c6191e95.png)

**Comment by laeubi** [comment]
Okay, It seems for the current implementation it is required to choose `test` dependency scope.

**Comment by laeubi** [comment]
@akurtakov see https://github.com/eclipse-m2e/m2e-core/discussions/461

**Comment by laeubi** [comment]
@mickaelistria I think this is something to consider for 2.7 as well and for the m2e release also.

**Comment by laeubi** [comment]
m2e change is done, will prepare now for tycho as well. The new syntax then would be  `includeDependencyScopes="compile,runtime"` to include both.
