### ISSUE TITLE
2.7.0-SNAPSHOT dirties project dir with .tycho-consumer-pom.xml

### ISSUE THREAD

**Issue by urld** [eclipse/tycho#664]
The current snapshot build (tycho-maven-plugin-2.7.0-20220212.084525-69) dirties the project dir with `.tycho-consumer-pom.xml`.
I think this should be somewhere nested in the target dir where `mvn clean` can remove it, but it wont get packaged.

**Comment by urld** [comment]
I understand, but isn't that unusual that maven plugins put generated files in the project source? As of now i only have `target/` in my .gitignore and never see any generated files. So i expected that if its strictly necessary for a plugin to have stuff outside of its build dir that the plugin will take care of cleaning it up afterwards.

**Comment by laeubi** [comment]
Probably yes :-) I have no idea if it would be needed for incremental builds or something like that?

**Comment by laeubi** [comment]
I'll mark them as deleteonexit with an option to disable the behavior...

**Comment by HannesWell** [comment]
Thanks!

**Comment by estepper** [comment]
I just accidentally pushed some of these new files.

It would be so nice if all these fancy new "features" wouldn't be activated by default by their developers, at least when they have a questionable persistent effect! Why do you think that everybody wants to make use of these new files? It's not even documented how exactly I can turn their creation off (correct me if I'm wrong).

How exactly can I avoid their creation at all?

**Comment by laeubi** [comment]
@estepper please use https://github.com/eclipse-tycho/tycho/discussions for usage questions, if you don't need 

> fancy new "features"

feel free to use older Tycho versions, they are retained forever thanks to maven central.

And you can't turn them off, as they server a purpose, but you can of course disable the generation of consumer poms directly see:

https://tycho.eclipseprojects.io/doc/latest/tycho-packaging-plugin/update-consumer-pom-mojo.html#skipPomGeneration

but you need to decide whether or not this is relevant for your setup.

Beside that, if you feel something is missing documentation we are always welcome contribution to improve the documentation and you can give feedback here:

- https://github.com/eclipse-tycho/tycho/discussions/1597

**Comment by estepper** [comment]
Your world is so simple. But I'm not always free to use the version I used to be happy with earlier. Have a look at https://www.eclipse.org/lists/cross-project-issues-dev/msg19409.html to see why I felt forced to bump my Tycho version.

Your hint with <skipPomGeneration>true</skipPomGeneration> sounds interesting, but my attempt to use it had no effect. Probably because I'm using it wrongly:

`    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.eclipse.tycho</groupId>
          <artifactId>tycho-packaging-plugin</artifactId>
          <version>${tycho-version}</version>
          <configuration>
            <skipPomGeneration>true</skipPomGeneration>
             ....
          </configuration>
`

How would I use it correctly?

IMO., no need to enhance the documentation of tycho-packaging-plugin then. I just didn't know what plugin was creating these files...

**Comment by laeubi** [comment]
> Your world is so simple. But I'm not always free to use the version I used to be happy with earlier.

As simple as "why can't you just turn of everything by default"... We try to choose defaults that are most likely useful and recommended for new builds, but we can't retain all and everything forever if it do not harm. Still there are always options for those who need to upgrade to restore old behavior as much as possible if they feel suitable.

And in this particular example the files should be deleted on exit, so unless you kill your builds... There is a long outstanding issue at Eclipse that terminating builds do not execute the shutdown actions (and thus do not delete files marked for deletion), so nothing much Tycho can do beside recommend updating your `.gitignores`

> How would I use it correctly?

from the snippet, I can't see any obvious reason, probably you want to open a question at https://github.com/eclipse-tycho/tycho/discussions with a runnable example, e.g tycho uses it this way:

https://github.com/eclipse-tycho/tycho/blob/ee5e17165eb565af2c0e74841eccbe99848949f7/tycho-bundles/pom.xml#L58-L65

**Comment by estepper** [comment]
I didn't suggest to "turn of **everything** by default". I would think that generating artifacts into a project's root folder is at least uncommon for Maven builds, if not even unrecommended. So, if you're changing existing functionality to do it nevertheless, you should make that new function an opt-in, and not an opt-out.

Yes, sometimes I kill a build. It's clear that shutdown actions may not be executed correctly. That's why a build should not create artifacts in the project root folder.

I did more testing with <skipPomGeneration> and it turns out that it DOES work as expected. I believe that the generated files I saw were left-overs from former tests. So that is great ;-)

**Comment by laeubi** [comment]
> I didn't suggest to "turn of **everything** by default". I would think that generating artifacts into a project's root folder is at least uncommon for Maven builds, if not even unrecommended.

It is required to do so because otherwise maven plugins are confused, for the same reason the https://www.mojohaus.org/flatten-maven-plugin/plugin-info.html do it the same way. So nothing much Tycho can do here if you don't want to break maven itself in several places.

What is **not uncommon** is, that one assumes file starting with a dot as "hidden", "system" and/or probably not to account for check into version control systems.

> I did more testing with "skipPomGeneration" and it turns out that it DOES work as expected. I believe that the generated files I saw were left-overs from former tests. So that is great ;-)

That's good to know.

**Comment by estepper** [comment]
> > I didn't suggest to "turn of **everything** by default". I would think that generating artifacts into a project's root folder is at least uncommon for Maven builds, if not even unrecommended.
> 
> It is required to do so because otherwise maven plugins are confused, for the same reason the https://www.mojohaus.org/flatten-maven-plugin/plugin-info.html do it the same way. So nothing much Tycho can do here if you don't want to break maven itself in several places.

If you say so. I don't mind as long as I can opt out at least. Opting in would, of course, be preferrable.

> What is **not uncommon** is, that one assumes file starting with a dot as "hidden", "system" and/or probably not to account for check into version control systems.

That's also an assertion without proof. And an unreasonable one, too, IMHO.

**Comment by HannesWell** [comment]
> > I didn't suggest to "turn of **everything** by default". I would think that generating artifacts into a project's root folder is at least uncommon for Maven builds, if not even unrecommended.
> 
> It is required to do so because otherwise maven plugins are confused, for the same reason the https://www.mojohaus.org/flatten-maven-plugin/plugin-info.html do it the same way. So nothing much Tycho can do here if you don't want to break maven itself in several places.
> 

For clarification, it is not possible to generate the .tycho-consumer-pom.xml into the `target` folder? Your answer seems to imply that, but I wanted to be sure.

**Comment by laeubi** [comment]
> For clarification, it is not possible to generate the .tycho-consumer-pom.xml into the `target` folder? Your answer seems to imply that, but I wanted to be sure.

For sure you can generate it everywhere, but it will break maven for example as it is assumed that the parent is stored relative to the pom. so if you use any subfolder, other maven components will complain. Also setting the pom location changes the basedir, so suddenly your basdir changes to the subfolder then, what also creates all kind of issues as now components searching relative to the basedir no longer find there files.

Actually it was first implemented that way, and I added some "hacks" to Tycho to mitigate some of these problems, but that do not work for external plugins and we got some bugreports about that.

Because of that, we now generate the file in the project root, what is not always nice but easily manageable.
