### ISSUE TITLE
Setting `-Dtest` on CLI cause build failure on eclipse-plugin

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#95]
Since https://github.com/eclipse/tycho/commit/d9a58240820776f11feb0a8dbaabfaaa00a4619d , one cannot use `-Dtest=...` flag any more on CLI as it will make regular `eclipse-plugin` build fail with "No tests found".
This use-case seems to be relatively commonly used, so this is a regression that should be mitigated.

**Comment by laeubi** [comment]
@mickaelistria Where do I find documentation about -Dtest=... (e.g. values to use as ...?)

**Comment by laeubi** [comment]
I think I found it: https://www.eclipse.org/tycho/sitedocs/tycho-surefire-plugin/test-mojo.html#test is that what you mean? Do you have an example I can use for testing?

**Comment by mickaelistria** [comment]
For example, with rt.equinox.p2 repo, you can try `mvn clean install -Pbuild-individual-bundles -Dtest=BaseChange`. The expected behavior is that all modules before the test build fine, and then test will only run BaseChange.

**Comment by laeubi** [comment]
I'll take a look at it.

**Comment by laeubi** [comment]
This is intentional but (from my point of view) badly documented.[ Surefire docu](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test) says for test that

> This parameter overrides the parameter includes, excludes, and the TestNG parameter suiteXmlFiles. 

but in fact it enables also a check that tests are run (most probably this is expected to be used not on the root level). Sad enough the error message 

> No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)

is misleading as [failIfNoTests](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#failIfNoTests) is false by default.

Instead one should specify [failIfNoSpecifiedTests](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#failIfNoSpecifiedTests), I have[ raised a bug](https://issues.apache.org/jira/browse/SUREFIRE-1910) for this.

So running `mvn clean install -Pbuild-individual-bundles -Dtest=BaseChange -Dsurefire.failIfNoSpecifiedTests=false` should do the trick, if you think that is useful we could try to set this property (if not specified) to false by default in the project setup.

**Comment by mickaelistria** [comment]
OK, I see this is consistent with maven-surefire-plugin.
It's a bit annoying as it basically breaks 1 useful workflow, but there are solutions (eg set test parameter in the pom.xml, combine install then verify...), so I think it's fine to just keep things as they are now in master. and don't try to support this former workflow.

**Comment by laeubi** [comment]
Alright then I think this could be closed

**Comment by laeubi** [comment]
I also added a warning note to the [RELEASE_NOTES](https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md)
